name: SonarQube Analysis

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  sonarqube:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Download logback
        run: |
          mkdir -p ./sonar-scanner-cli/lib
          curl -L https://repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar --output ./sonar-scanner-cli/lib/logback-classic-1.2.3.jar

      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: npx sonarqube-scanner
          -Dsonar.projectKey=npm
          -Dsonar.sources=.
          -Dsonar.host.url=$SONAR_HOST_URL
          -Dsonar.login=$SONAR_TOKEN

      - name: Upload coverage to SonarQube
        if: success()
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          npx sonarqube-scanner
            -Dsonar.projectKey=npm
            -Dsonar.sources=.
            -Dsonar.host.url=$SONAR_HOST_URL
            -Dsonar.login=$SONAR_TOKEN
