name: SonarQube Analysis

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  sonarqube:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci
          npm install logback@3.2.0

      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          mkdir -p ./sonar-scanner-cli/lib
          cp ./node_modules/logback/lib/logback-classic-1.2.3.jar ./sonar-scanner-cli/lib
          npx sonarqube-scanner
            -Dsonar.projectKey=npm
            -Dsonar.sources=.
            -Dsonar.host.url=$SONAR_HOST_URL
            -Dsonar.login=$SONAR_TOKEN

      - name: Upload coverage to SonarQube
        if: success()
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          npx sonarqube-scanner
            -Dsonar.projectKey=npm
            -Dsonar.sources=.
            -Dsonar.host.url=$SONAR_HOST_URL
            -Dsonar.login=$SONAR_TOKEN
